# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widgetIzquierda = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetIzquierda.setGeometry(QtCore.QRect(-1, -1, 191, 571))
        self.widgetIzquierda.setStyleSheet("background-color:rgb(206, 151, 0);")
        self.widgetIzquierda.setObjectName("widgetIzquierda")
        self.btnImprimir = QtWidgets.QPushButton(parent=self.widgetIzquierda)
        self.btnImprimir.setGeometry(QtCore.QRect(20, 120, 151, 61))
        self.btnImprimir.setStyleSheet("background-color:rgb(180, 180, 180);\n"
"font-size: 20px;")
        self.btnImprimir.setObjectName("btnImprimir")
        self.btnFichar = QtWidgets.QPushButton(parent=self.widgetIzquierda)
        self.btnFichar.setGeometry(QtCore.QRect(20, 40, 151, 61))
        self.btnFichar.setStyleSheet("background-color:rgb(180, 180, 180);\n"
"font-size: 20px;\n"
"")
        self.btnFichar.setObjectName("btnFichar")
        self.widgetAbajo = QtWidgets.QWidget(parent=self.centralwidget)
        self.widgetAbajo.setGeometry(QtCore.QRect(189, 419, 611, 161))
        self.widgetAbajo.setStyleSheet("background-color:rgb(151, 0, 206);")
        self.widgetAbajo.setObjectName("widgetAbajo")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.widgetAbajo)
        self.buttonBox.setGeometry(QtCore.QRect(400, 30, 193, 71))
        self.buttonBox.setStyleSheet("background-color:rgb(180, 180, 180);")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.textEdit = QtWidgets.QTextEdit(parent=self.widgetAbajo)
        self.textEdit.setGeometry(QtCore.QRect(30, 10, 351, 101))
        self.textEdit.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.textEdit.setObjectName("textEdit")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(190, 0, 611, 421))
        self.stackedWidget.setStyleSheet("background-color:rgb(0, 206, 151);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.page)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 70, 461, 99))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setStyleSheet("font-size: 30px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.horizontalLayoutWidget)
        self.dateEdit.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font-size: 30px;")
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_5.setStyleSheet("font-size: 30px;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.horizontalLayoutWidget)
        self.dateEdit_2.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"font-size: 30px;")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.verticalLayout_2.addWidget(self.dateEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(parent=self.page)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(70, 220, 251, 151))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(parent=self.verticalLayoutWidget_3)
        self.label_6.setStyleSheet("font-size: 20px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.listView = QtWidgets.QListView(parent=self.verticalLayoutWidget_3)
        self.listView.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.listView.setObjectName("listView")
        self.verticalLayout_3.addWidget(self.listView)
        self.pushButton = QtWidgets.QPushButton(parent=self.page)
        self.pushButton.setGeometry(QtCore.QRect(390, 270, 93, 28))
        self.pushButton.setStyleSheet("background-color:rgb(180, 180, 180);\n"
"font-size: 20px;")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.btnEmitirFichaje = QtWidgets.QPushButton(parent=self.page_2)
        self.btnEmitirFichaje.setGeometry(QtCore.QRect(230, 320, 151, 61))
        self.btnEmitirFichaje.setStyleSheet("background-color:rgb(180, 180, 180);\n"
"font-size: 20px;")
        self.btnEmitirFichaje.setObjectName("btnEmitirFichaje")
        self.textEditHora = QtWidgets.QTextEdit(parent=self.page_2)
        self.textEditHora.setGeometry(QtCore.QRect(330, 60, 251, 87))
        self.textEditHora.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.textEditHora.setObjectName("textEditHora")
        self.textEditFecha = QtWidgets.QTextEdit(parent=self.page_2)
        self.textEditFecha.setGeometry(QtCore.QRect(50, 60, 251, 87))
        self.textEditFecha.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.textEditFecha.setObjectName("textEditFecha")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.page_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(50, 170, 401, 89))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        self.label.setStyleSheet("font-size: 30px;")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.horizontalLayoutWidget_2)
        self.textEdit_3.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_2.addWidget(self.textEdit_3)
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnImprimir.setText(_translate("MainWindow", "imprimir"))
        self.btnFichar.setText(_translate("MainWindow", "fichar"))
        self.label_2.setText(_translate("MainWindow", "Fecha desde"))
        self.label_5.setText(_translate("MainWindow", "Fecha hasta"))
        self.label_6.setText(_translate("MainWindow", "Estado trabajadores"))
        self.pushButton.setText(_translate("MainWindow", "Imprimir"))
        self.btnEmitirFichaje.setText(_translate("MainWindow", "Emitir Fichaje"))
        self.textEditHora.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">HH : MM</span></p></body></html>"))
        self.textEditFecha.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Dia / Mes / Año</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Teclea tu código"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
